name: Deploy Firebase (Auth/Firestore/Hosting only)

on:
  push:
    branches: [main]
    paths:
      - "firestore.rules"
      - "firestore.indexes.json"
      - "firebase.json"
      - "public/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,firestore:indexes,hosting
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
